{% set name = "crochet" %}
{% set version = "2.0.0" %}
{% set sha256 = "5f7f6c0d41ec418da16080f0202faac6b30f84a6fca9d8911e9db541f8e4e521" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - python >=3.6
    - twisted >=15.0
    - wrapt

test:
  imports:
    - crochet

about:
  home: https://github.com/itamarst/crochet
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Use Twisted anywhere!
  description: |
    Crochet is an MIT-licensed library that makes it easier to use Twisted from
    regular blocking code. Some use cases include:

      * Easily use Twisted from a blocking framework like Django or Flask.

      * Write a library that provides a blocking API, but uses Twisted for its
        implementation.

      * Port blocking code to Twisted more easily, by keeping a backwards
        compatibility layer.

      * Allow normal Twisted programs that use threads to interact with Twisted
        more cleanly from their threaded parts. For example, this can be useful
        when using Twisted as a WSGI container.
  doc_url: https://crochet.readthedocs.org/
  dev_url: https://github.com/itamarst/crochet/

extra:
  recipe-maintainers:
    - stuertz
    - itamarst
