{% set name = "crochet" %}
{% set version = "1.10.0" %}
{% set sha256 = "de0d1c9acfe8200b7ec8cf53ce5878fd20531d55c01199a9ae27936c45ef3c79" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python

  run:
    - python
    - twisted >=15.0
    - wrapt
    
test:
  imports:
    - crochet

about:
  home: https://github.com/itamarst/crochet
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Use Twisted anywhere!'
  description: |
    Crochet is an MIT-licensed library that makes it easier to use Twisted from
    regular blocking code. Some use cases include:

      * Easily use Twisted from a blocking framework like Django or Flask.

      * Write a library that provides a blocking API, but uses Twisted for its
        implementation.

      * Port blocking code to Twisted more easily, by keeping a backwards
        compatibility layer.

      * Allow normal Twisted programs that use threads to interact with Twisted
        more cleanly from their threaded parts. For example, this can be useful
        when using Twisted as a WSGI container.
  doc_url: https://crochet.readthedocs.org/
  dev_url: https://github.com/itamarst/crochet/

extra:
  recipe-maintainers:
    - stuertz
    - itamarst
