travis:
  secure:
    BINSTAR_TOKEN: VkauV5PTA0QhGqLo1A4Hz++lb/fjSyuU2eBhutOtGocyiqQJKyMxW4lJY7UM78++PirXdEvut8DfKih4hY0lbkWdoR2MICfJMGxC/h4iCgNRcKdDc1cZPrvJ1S6iC5OuFVm2Kc9qVwtIGedfae4yo0rYk5jKy6M5ztU1q6HlrtKQULwM4e9xZdySXgYx/fMWPziwuTSD/HdBG/pPfkLAsDdSJTqlYlVN8RmrHBjEVqPEk1SUUfOwziESAxuNd0qONki9ymTGurIu3ZlcLXJ5l92G1V1ISKpBuAZk83IU6+G/RPXaUvVmX1hhBGyufPz7/6dNbefYRKAzKSO6YwfHVPYHNWjkJX+I99WbbZLXGpbNrzGSi6y26bnuD1YAMxByire/jvK0GYSfm+45fC5P7Y46xZKbR/SSLNN0N3k3hY44OKvOWd7snqJfBPObLrRfMJ9ZnccxuIHyq55HdJtFGvDTa+WdOBP9c/g/VqoScjwPPuXF1+j2MXMUuvlbW0fE38IegpTlj1hSXtgOCZYLSHSR0EU5yzTVCfAp+7FCOmzYWyLPPi1jIkdMl+xLc3LEBCNZPX6isu+7w4Ib5JGRXE8+4dcJn+KmBtd1ExM/jDoQaCSZu0a3WQdkpI9kXeMPlNQ6WgDJDUYThB0EZZtTHMmO1Vea0tggfmLL0f1ciaU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
