travis:
  secure:
    BINSTAR_TOKEN: doWmDg2JR7hbKNs4746LcG3NiMaDY9saR8VWIiS1E1uFAC7d95a2hUfNDON/RDl9LsbRTPKNWutLOtUv2D4HV3b60i2bNoAYMBKTB6MrcqZOQ/NNBuX2HrwcPWEB21jxEPTox9Hx9YCSTk2ruRiRn8l4viR5NrZq5h3ETb2YQIj+I4nSSzw0rebV2JrQD6BlsGUMVy4zj3SW4sK2W/yfFz2/593V1JTrHvOHW3JIOXSCAvxA2ZnMPCoqwBvdxvUFWYQIXGRulz11OvhLT5RZZ8uNpdFztSpV5SBDSghRbkBRfQo11Y49ajYOH0YUiXI/SgGXeOmIHtUg9kdzW/HzP/szoCJrUed7NrrmYKRUL5hDAGlTvr9kYkOR+03fkIYHnptaz/V7Q/g25wP2WkVazXwL0FgphVmF0sG7oOOK9Fl01eE6hzIAl684pjeHnUBUpttXvP7IVCFdQTSApTiV6/jXuIt9fbVXLAAuy4W00Kn1UBdqMqUGayOFIrRVHxkrFK2VMObVdR7q4A57zvQhUzqYVOnYQEwKpSyOuC9Hmj7E5ushnoMFepJ5RzEWPgRU/b5sMKLZRZI8MF+3b/1tu3zxw/cblnl36HL5aMAL+a4kzr9tej+nm5Bty0BcEVpHjqlGVRrBTZ1eFkiiLOvitIfeiMo/dWEHBIn2tFJMKWc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
